#ifndef ATPCOMMON_H
#define ATPCOMMON_H
//fixed parameters
#define USE_AGTR_COUNT 1200
#define INITIAL_WINDOW_SIZE 100
#define MAX_AGTR_COUNT 40000
#define TXDEVICE_THRESHOLD 1000 // total 2kp
#define P4ML_PACKET_SIZE 260 // 248 + 12
#define P4ML_DATA_SIZE 248
#define MAX_ENTRIES_PER_PACKET 62
#define TIMEOUT 0.05
#define FAST_TRANSMISSION_THRESHOLD 3
#define MAX_RETRANSMISSION_TIMES 1
#define PS_BUFFER_TIMEOUT 0.5
#define PS_BUFFER_SIZE 65536
#define TXDEVICE_ID 2
//key parameters
#define MAX_BYTES 100 * P4ML_PACKET_SIZE
#endif